### ISSUE TITLE
Exception in thread "main" java.lang.StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by ghost** [lndmflngs/line-to-telegram#1]
Hi, I'm getting the following error when running the program:

```cmd
C:\path\to\jar\file> java -jar line-to-telegram.jar https://store.line.me/stickershop/product/1439/en
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -58
        at java.lang.String.substring(Unknown Source)
        at model.Sticker.getName(Sticker.kt:9)
        at LineToTelegramKt.main(LineToTelegram.kt:12)
```

The folder is created according to the sticker packs name, though nothing is saved and ends abruptly.

**Comment by gj94gj94ao4** [comment]
same problem.  QQ

**Comment by Manekineko-mk1** [comment]
> same problem. QQ

I've forked the repo and should fixed the problem. Try it and let me know?

**Comment by Lann094** [comment]
> I've forked the repo and should fixed the problem. Try it and let me know?

Your fork fixed it up nicely, thanks Jesse. Building was a bit of a mission, but I'm not sure if that was just thanks to my inexperience.

**Comment by peirantan** [comment]
> > same problem. QQ
> 
> I've forked the repo and should fixed the problem. Try it and let me know?

Can I get a copy of ur jar too? Encountered the exact same problem.

**Comment by imbeerus** [comment]
sorry for late response. now it's fine
thanks @JesseTsang  for your work

**Comment by al3xtjames** [comment]
This issue occurs again. It appears LINE made `ANDROID` lowercase in the sticker URLs.

https://github.com/lndmflngs/line-to-telegram/blob/583fb4085f85607d03519ba5638ddc6ea2f44c8c/src/main/java/model/Sticker.kt#L7

Changing this to `android` fixes it.
