### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException

### ISSUE THREAD

**Issue by Roshri** [lndmflngs/line-to-telegram#5]
I'm trying to download a set of stickers https://store.line.me/stickershop/product/9608/en and can't do it.  I get the following error. I get the same when I try to download the one used as example in #2
Found the same error while downloading https://store.line.me/stickershop/product/11769/es

Exception in thread "main" java.lang.NullPointerException
        at utils.JsoupUtils.getPackTitle(JsoupUtils.kt:67)
        at model.Pack.<init>(Pack.kt:9)
        at LineToTelegramKt.main(LineToTelegram.kt:10)

**Comment by imbeerus** [comment]
Thanks for your help, issue resolved :)

Here is your sticker packs:
[Princessconnect  ReDive.zip](https://github.com/lndmflngs/line-to-telegram/files/4223278/Princessconnect.ReDive.zip)
[THE IDOLMSTER Million Live Chibi Ver.zip](https://github.com/lndmflngs/line-to-telegram/files/4223279/THE.IDOLMSTER.Million.Live.Chibi.Ver.zip)
