### ISSUE TITLE
Add .TGS support?

### ISSUE THREAD

**Issue by agentben96** [lndmflngs/line-to-telegram#6]
Can we possibly add support for [TGS animated stickers](https://core.telegram.org/animated_stickers) as an output?
Such as converting animated Line sticker (ex: https://store.line.me/stickershop/product/5835/en) into tgs animated 30fps or 60fps stickers for telegram? 

Maybe we tell the .jar we're doing animated stickers with a parameter? 
or maybe it auto detect if the sticker is animated already.

**Comment by imbeerus** [comment]
I'll think about it. Thank you for the idea.)
